# Generated by Django 5.1.1 on 2024-10-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='პროდუქტის სახელი')),
                ('price', models.IntegerField(verbose_name='ფასი')),
                ('category', models.ManyToManyField(to='store.category', verbose_name='კატეგორიები')),
            ],
        ),
    ]
