# Generated by Django 5.1.1 on 2024-10-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='პროდუქტის ფოტო'),
        ),
    ]
