# Generated by Django 5.1.1 on 2024-10-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_product_add_date_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
