# Generated by Django 5.1.1 on 2024-10-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_description_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='პროდუქტის აღწერა'),
        ),
    ]
