# Generated by Django 5.1.1 on 2024-10-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20241020_2326'),
    ]

    operations = [
    ]
