# Generated by Django 5.1.1 on 2024-10-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_category_level_category_lft_category_rght_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preparation_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='მომზადების დრო წამებში'),
        ),
        migrations.AddField(
            model_name='product',
            name='servings',
            field=models.IntegerField(blank=True, null=True, verbose_name='ულუფა'),
        ),
    ]
