# Generated by Django 5.1.1 on 2024-10-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_preparation_time_product_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='servings',
            field=models.IntegerField(blank=True, default=0, verbose_name='ულუფა'),
        ),
    ]
