# Generated by Django 5.1.1 on 2024-11-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_tag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='კატეგორიის სახელი'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ka',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='კატეგორიის სახელი'),
        ),
    ]
