# Generated by Django 5.1.1 on 2024-11-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='ბოლო აქტიურობა'),
        ),
    ]
