# Generated by Django 5.1.1 on 2024-10-23 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_usercart_created_at_item'),
        ('store', '0018_tag_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.usercart', verbose_name='მომხმარებლის კალათა'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='პროდუქტი'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='რაოდენობა'),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='კალათის შექმნის დრო'),
        ),
    ]
